name: cafo-pytorch
channels:
  - conda-forge
dependencies:
  - cudatoolkit=11.0
  - fiona
  - gdal>3.0
  - ipykernel
    #- matplotlib
    #- numpy
    #- osmnx
    #- pandas
  - pip
  - python
  - pytorch-gpu
  # - rasterio
    #- rtree
    #- scikit-image
    #- scikit-learn
    #- shapely
    # - torchvision
  - pip:
    - black>=21.4b0
    - flake8>=3.8
    - isort[colors]>=5.8
    - mypy>=0.900
    - parse
    - segmentation-models-pytorch>=0.2
    - tensorboard
    # moved packages
    - matplotlib
    - numpy
    - osmnx
    - pandas
    - rtree
    - scikit-image
    - scikit-learn
    - shapely
    - torchvision
    # rasterio is finicky try it all with pip
    # - fiona
    # - gdal>3
    - rasterio
    # maybe add folium also
    # and maybe need charset_normalizer » chardet